@echo off
rmdir /S /Q results
md results
if EXIST xaui_v10_4_example_design.ngc del /Q xaui_v10_4_example_design.ngc
REM -------------------------------------------------
REM Design Flow
REM -------------------------------------------------
echo Synthesizing example design with XST
xst -ifn xst.scr
copy xaui_v10_4_example_design.ngc results
REM -------------------------------------------------
REM Copy the netlist generated by Coregen
REM -------------------------------------------------
echo Copy files from the netlist directory to the results directory
cd results
copy ..\..\..\xaui_v10_4.ngc xaui_v10_4.ngc

rem  Copy the constraints files generated by Coregen
echo Copying files from constraints directory to the results directory
copy ..\..\example_design\xaui_v10_4_example_design.ucf .

echo Running ngdbuild
ngdbuild xaui_v10_4_example_design

echo Running map
map xaui_v10_4_example_design -o mapped.ncd

echo Running par
par -ol high mapped.ncd routed mapped.pcf

echo Running trce
trce -e 10 routed -o routed mapped.pcf

echo Running bitgen
bitgen  -j  routed.ncd routed.drc mapped.pcf

echo Running netgen to create gate level model
netgen -ofmt verilog -pcf mapped.pcf -sim -dir . -tm xaui_v10_4_example_design -sdf_anno false  routed.ncd routed.v

REM End of batch file.
REM -------------------------------------------------
