#!/bin/sh

# Clean up the run directory
rm -rf results
mkdir results
rm -f xaui_v10_4_example_design.ngc

#####################################################
# Design Flow
####################################################
echo Synthesizing example design with XST
xst -ifn xst.scr
cp xaui_v10_4_example_design.ngc results

#####################################################
# Copy the netlist generated by Coregen
#####################################################
echo 'Copying the CoreGEN generated netlist to the results directory'
cd results
cp ../../../xaui_v10_4.ngc xaui_v10_4.ngc

#  Copy the constraints files generated by Coregen
echo 'Copying constraints file from example design directory to the results directory.'
cp ../../example_design/xaui_v10_4_example_design.ucf .

echo 'Running ngdbuild'
ngdbuild xaui_v10_4_example_design

echo 'Running map'
map -detail xaui_v10_4_example_design -o mapped.ncd

echo 'Running par'
par -ol high mapped.ncd routed mapped.pcf

echo 'Running trce'
trce -e 10 routed -o routed mapped.pcf

echo 'Running design through bitgen'
bitgen  -j  routed.ncd routed.drc mapped.pcf 

echo 'Running netgen to create gate level model'
netgen -ofmt verilog -pcf mapped.pcf -sim -dir . -tm xaui_v10_4_example_design  -sdf_anno false routed.ncd routed.v
#####################################################
